name: Run Tests

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, autotest ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  python-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r src/tests/requirements.txt
          pip install -e .

      - name: Run all tests
        run: python -m unittest discover -s src/tests
